from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import io
from datetime import datetime
import cv2
import numpy as np
from PIL import Image

def generate_status_pdf(plan_name, original_img_rgb, stats):
    """
    יוצר דוח PDF מפורט עם תמונת סטטוס ונתונים
    
    Args:
        plan_name: שם התוכנית
        original_img_rgb: תמונה עם סימון ירוק של מה שבוצע
        stats: מילון עם: built, total, percent, remaining, cost, budget
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=landscape(A4))
    width, height = landscape(A4)
    
    # === כותרת ראשית ===
    c.setFont("Helvetica-Bold", 28)
    c.drawString(50, height - 50, "ConTech Pro - Project Status Report")
    
    c.setFont("Helvetica", 14)
    c.drawString(50, height - 75, f"Project: {plan_name}")
    c.drawString(50, height - 95, f"Report Date: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
    
    # === קו הפרדה ===
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.setLineWidth(2)
    c.line(50, height - 105, width - 50, height - 105)
    
    # === סטטיסטיקות ===
    c.setFont("Helvetica-Bold", 16)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(50, height - 135, "Progress Summary")
    
    c.setFont("Helvetica", 12)
    
    # שורה 1: התקדמות
    y_pos = height - 160
    c.setFillColorRGB(0.2, 0.6, 0.2)  # ירוק
    c.drawString(50, y_pos, f"Completed: {stats.get('built', 0):.1f} m")
    
    c.setFillColorRGB(0, 0, 0)
    c.drawString(200, y_pos, f"Total Scope: {stats.get('total', 0):.1f} m")
    
    c.setFillColorRGB(0.8, 0.4, 0)  # כתום
    c.drawString(350, y_pos, f"Remaining: {stats.get('remaining', 0):.1f} m")
    
    # שורה 2: אחוז התקדמות
    y_pos -= 25
    percent = stats.get('percent', 0)
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_pos, f"Progress: {percent:.1f}%")
    
    # פס התקדמות ויזואלי
    bar_x = 180
    bar_y = y_pos - 5
    bar_width = 300
    bar_height = 20
    
    # רקע (אפור)
    c.setFillColorRGB(0.9, 0.9, 0.9)
    c.rect(bar_x, bar_y, bar_width, bar_height, fill=1, stroke=0)
    
    # התקדמות (ירוק)
    progress_width = (percent / 100) * bar_width
    c.setFillColorRGB(0.2, 0.8, 0.2)
    c.rect(bar_x, bar_y, progress_width, bar_height, fill=1, stroke=0)
    
    # מסגרת
    c.setStrokeColorRGB(0.5, 0.5, 0.5)
    c.setLineWidth(1)
    c.rect(bar_x, bar_y, bar_width, bar_height, fill=0, stroke=1)
    
    # שורה 3: תקציב
    y_pos -= 40
    c.setFont("Helvetica", 12)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(50, y_pos, f"Current Cost: {stats.get('cost', 0):,.0f} ILS")
    c.drawString(250, y_pos, f"Budget: {stats.get('budget', 0):,.0f} ILS")
    
    budget_variance = stats.get('budget', 0) - stats.get('cost', 0)
    if budget_variance >= 0:
        c.setFillColorRGB(0.2, 0.6, 0.2)
        c.drawString(450, y_pos, f"Under Budget: {budget_variance:,.0f} ILS")
    else:
        c.setFillColorRGB(0.8, 0.2, 0.2)
        c.drawString(450, y_pos, f"Over Budget: {abs(budget_variance):,.0f} ILS")
    
    # === קו הפרדה נוסף ===
    y_pos -= 20
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.setLineWidth(1)
    c.line(50, y_pos, width - 50, y_pos)
    
    # === תמונה ===
    try:
        # המרה ל-RGB בטוחה
        if len(original_img_rgb.shape) == 2:
            img_to_show = cv2.cvtColor(original_img_rgb, cv2.COLOR_GRAY2RGB)
        else:
            img_to_show = original_img_rgb.copy()
        
        # המרה ל-PIL
        img_pil = Image.fromarray(img_to_show)
        
        # שמירה לזיכרון כ-PNG
        img_byte_arr = io.BytesIO()
        img_pil.save(img_byte_arr, format='PNG')
        img_byte_arr.seek(0)
        
        img_reader = ImageReader(img_byte_arr)
        
        # חישוב פרופורציות
        img_w, img_h = img_pil.size
        aspect = img_h / float(img_w)
        
        # מקסימום שטח לתמונה
        display_width = width - 100
        display_height = y_pos - 60  # השאר מקום למטה
        
        # התאמה לפרופורציות
        calc_height = display_width * aspect
        if calc_height > display_height:
            calc_height = display_height
            display_width = calc_height / aspect
        else:
            display_height = calc_height
        
        # ציור התמונה
        img_y = 50  # מהתחתית
        c.drawImage(img_reader, 50, img_y, width=display_width, height=display_height)
        
        # מקרא
        c.setFont("Helvetica", 10)
        c.setFillColorRGB(0.2, 0.8, 0.2)
        c.drawString(50, img_y + display_height + 10, "Green = Completed Work")
        
    except Exception as e:
        c.setFont("Helvetica", 12)
        c.setFillColorRGB(0.8, 0.2, 0.2)
        c.drawString(50, height/2, f"Image Error: {str(e)}")
    
    # === Footer ===
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(50, 20, f"Generated by ConTech Pro | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawRightString(width - 50, 20, "Page 1 of 1")
    
    c.showPage()
    c.save()
    
    buffer.seek(0)
    return buffer
